In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
from matplotlib import pyplot as plt
from scipy.stats import linregress
from sklearn import linear_model

In [2]:
error = np.random.randn(10**4)
error

array([-0.36008048, -0.83145719, -1.26430409, ..., -0.79581379,
       -0.60303246, -0.61295254])

In [3]:
lng = 0.02+0.02*error
lng

array([ 0.01279839,  0.00337086, -0.00528608, ...,  0.00408372,
        0.00793935,  0.00774095])

In [4]:
g = np.exp(lng)
g

array([1.01288064, 1.00337654, 0.99472787, ..., 1.00409207, 1.00797095,
       1.00777099])

In [5]:
rf = 1.0303
b0 = np.arange(0,10.1,0.1)
b0

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [6]:
def v(x):
    v_list = []
    for i in g:
        if x*i>=1.0303:
            y = x*i-1.0303
        else:
            y = 2*x*i-1.0303
        v_list.append(y)
    return v_list

In [7]:
def e(x,b):
    output = 0.99*b*np.mean(v(x))+0.99*x-1
    return output

In [ ]:
x_list = []
for b in b0:
    upper = 1.1
    lower = 1.0
    output = e((upper+lower)/2, b)
    while abs(output) > 1e-5:
        if output>0:
            upper=(lower+upper)/2
            output = e((lower+upper)/2,b)
        else:
            lower=(lower+upper)/2
            output = e((lower+upper)/2,b)
    x_list.append((upper+lower)/2)